"""empty message

Revision ID: 7f3269420eef
Revises: 6c1bfaf49c6c
Create Date: 2019-03-27 09:15:41.235336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f3269420eef'
down_revision = '6c1bfaf49c6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
